language: python
dist: bionic
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
branches:
  only:
    - develop
install:
  - "pip install codecov pytest pytest-cov"  # required for tests
  - "pip install ."
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.9' ]]; then pip install sphinx check-manifest flake8; fi"
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.9' ]]; then check-manifest; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.9' ]]; then flake8; fi"
  - "pushd doc"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.9' ]]; then make html; fi"
  - "popd"
  - "pushd test"
  - "pytest --cov=sphinxcontrib.bibtex --cov=natbib"
  - "popd"
  - "pytest --cov=pybtex_docutils"
after_success:
  - "pushd test"
  - "codecov"
  - "popd"
